## Machine learning in linear regression

#### BUSINESS UNDERSTANDING

In [17]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
insurance_details=pd.read_csv(filepath_or_buffer="insurance data.csv")
insurance_details

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

#### DATA UNDERSTANDING

In [3]:
insurance_details.shape

(1340, 7)

In [4]:
insurance_details.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [5]:
insurance_details.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [6]:
insurance_details.describe()

,CASENUM,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
count,1340.000000,1340.000000,1328.000000,1299.000000,1292.000000,1151.000000,1340.000000
mean,11202.001493,0.488806,0.558735,0.907621,0.017028,28.414422,3.806307
std,9512.750796,0.500061,0.496725,0.289671,0.129425,20.304451,10.636903
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4177.000000,0.000000,0.000000,1.000000,0.000000,9.000000,0.400000
50%,8756.500000,0.000000,1.000000,1.000000,0.000000,30.000000,1.069500
75%,15702.500000,1.000000,1.000000,1.000000,0.000000,43.000000,3.781500
max,34153.000000,1.000000,1.000000,1.000000,1.000000,95.000000,173.604000

#### DATA PREPARATION

In [7]:
insurance_details.dropna(inplace=True)
insurance_details

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1334    34104         1     1.0       1.0       0.0    16.0   0.060
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1096 rows x 7 columns]

In [8]:
x=insurance_details.drop(labels=["CASENUM","ATTORNEY"],axis=1)
x

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [9]:
y=insurance_details[["ATTORNEY"]]
y

      ATTORNEY
0            0
1            1
2            1
3            0
4            1
...        ...
1334         1
1336         0
1337         1
1338         0
1339         1

[1096 rows x 1 columns]

In [10]:
x.shape

(1096, 5)

In [11]:
x.isna().sum()

CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [12]:
y.shape

(1096, 1)

In [13]:
y.isna().sum()

ATTORNEY    0
dtype: int64

#### MODEL BUILDING

In [32]:
from sklearn.linear_model import LogisticRegression
logistic_model=LogisticRegression()

#### MODEL TRAINING

In [33]:
logistic_model.fit(x,y)

LogisticRegression()

#### MODEL TESTING

In [34]:
logistic_model.intercept_

array([-0.17354511])

In [35]:
logistic_model.coef_

array([[ 0.42687938,  0.57060554, -0.59469538,  0.00653926, -0.38425089]])

In [36]:
logistic_model.fit_intercept

True

In [37]:
y_pred=logistic_model.predict(x)
print(y_pred)

[0 1 1 ... 1 0 1]

#### MODEL EVALUATION

In [29]:
from sklearn.metrics import accuracy_score

In [38]:
accuracy_score(y_true=y, y_pred=y_pred)

0.708029197080292

#### MODEL DEPLOYMENT

In [56]:
from pickle import dump
dump(obj=logistic_model,file=open("claimants.pkl","wb"))
from pickle import load
linear_intel_pkl = load(file=open("claimants.pkl","rb"))
print(linear_intel_pkl.predict(x))

[0 1 1 ... 1 0 1]

### THE END

=========================================================================================================================================